In [ ]:
print('Hello world')

Hello world

In [49]:
import pandas as pd

# Criar um data frame(trazer os dados para a memória do python)

df = pd.read_csv('dados.csv')

display(df.head(2))


print('--------------------------------')
# print()
# print('def.info:')
print()

# info - apresenta um resumo do "dataset"
print(df.info)

print()
print('---------------------------------\n')

# 
print(df.describe())

# Mostra total de registros e colunas
print(df.shape)

print('\n')

print(df.columns)

       marca modelo     cor   ano  valor
0         vw  fusca  branco  1985  25000
1  chevrolet  opala   preto  1979  52500

--------------------------------

<bound method DataFrame.info of        marca   modelo     cor   ano   valor
0         vw    fusca  branco  1985   25000
1  chevrolet    opala   preto  1979   52500
2       fiat    marea   preto  2001   15680
3         vw  variant    bege  1985   10000
4        bmw     320i   prata  2017   80620
5      honda    civic   prata  2023  140000>

---------------------------------

               ano          valor
count     6.000000       6.000000
mean   1998.333333   53966.666667
std      18.402898   49703.702344
min    1979.000000   10000.000000
25%    1985.000000   18010.000000
50%    1993.000000   38750.000000
75%    2013.000000   73590.000000
max    2023.000000  140000.000000
(6, 5)


Index(['marca', 'modelo', 'cor', 'ano', 'valor'], dtype='str')

In [61]:
# Consultar apenas uma coluna 
marca =  df['marca']

print(marca)

print('\n')

# Consulta direto no print
print(df['modelo'])

print('\n')

# Consultar mais que uma coluna
marca_modelo_cor                       = df[['marca','modelo']]

display(marca_modelo_cor)

0           vw
1    chevrolet
2         fiat
3           vw
4          bmw
5        honda
Name: marca, dtype: str


0      fusca
1      opala
2      marea
3    variant
4       320i
5      civic
Name: modelo, dtype: str

       marca   modelo
0         vw    fusca
1  chevrolet    opala
2       fiat    marea
3         vw  variant
4        bmw     320i
5      honda    civic

In [ ]:
# Criar filtros

# quero saber quantos carros não pagam mais ipva no meu estoque
noIpva = df[df['ano'] < 2006 ]

display(noIpva)

# Apresente os carros que custam mais de R$ 20.000,00
preco = df[df['valor'] > 20000]

display(preco)

# Apresente apenas os carro da chevrolet
carrosChlet = df[df['marca'] == 'chevrolet']

display(carrosChlet)

       marca   modelo     cor   ano  valor
0         vw    fusca  branco  1985  25000
1  chevrolet    opala   preto  1979  52500
2       fiat    marea   preto  2001  15680
3         vw  variant    bege  1985  10000

       marca modelo     cor   ano   valor
0         vw  fusca  branco  1985   25000
1  chevrolet  opala   preto  1979   52500
4        bmw   320i   prata  2017   80620
5      honda  civic   prata  2023  140000

       marca modelo    cor   ano  valor
1  chevrolet  opala  preto  1979  52500